import { FunctionTool, LlmAgent } from '@google/adk';
import { createAgentEndCallback, createAgentStartCallback } from './sub-agents/callbacks/performance-callback.js';
import {
  ANSWER_KEY,
  FEEDBACK_KEY,
  GAPS_GRADES_KEY,
  QUESTION_KEY,
  SUB_QUESTIONS_KEY,
} from './sub-agents/output-keys.const.js';
import { questionAnswerInputSchema } from './sub-agents/types/audit-feedback.type.js';
import { isValidFeedback } from './sub-agents/utils.js';
import { createAuditFeedbackAgent } from './workflow-agents/sequential-audit-feedback-agent.js';

process.loadEnvFile();

const model = process.env.GEMINI_MODEL_NAME || '';
if (!model) {
  throw new Error('GEMINI_MODEL_NAME is not set');
}

const prepareAuditFeedbackTool = new FunctionTool({
  name: 'prepare_audit_feedback',
  description:
    "Stores the audit question, the user's answer, and any optional feedback to prepare for the audit pipeline.",
  parameters: questionAnswerInputSchema,
  execute: ({ question, answer, feedback }, context) => {
    if (!context || !context.state) {
      return { status: 'ERROR', message: 'No session state found.' };
    }

    const minLength = 10;
    if (question.trim().length < minLength) {
      return {
        status: 'ERROR',
        message: 'The question is too short or invalid. Ask the user to provide a more detailed audit question.',
      };
    }

    if (answer.trim().length < 10) {
      return {
        status: 'ERROR',
        message: 'The answer is too short or invalid. Ask the user to provide a more detailed answer.',
      };
    }

    context.state.set(QUESTION_KEY, question);
    context.state.set(ANSWER_KEY, answer);

    if (isValidFeedback(feedback)) {
      context.state.set(FEEDBACK_KEY, feedback);
    } else {
      context.state.set(FEEDBACK_KEY, null);
    }

    // Always clear previous intermediate audit state to ensure a clean run
    context.state.set(SUB_QUESTIONS_KEY, null);
    context.state.set(GAPS_GRADES_KEY, null);

    return {
      status: 'SUCCESS',
      message:
        'System state has been updated. ' + (feedback ? 'Feedback incorporated.' : 'Previous feedback state reset.'),
    };
  },
});

export const rootAgent = new LlmAgent({
  name: 'AuditFeedbackAgent',
  model,
  description:
    'The primary orchestrator agent that manages user interaction for audit feedback. There is only one question and one answer to the question in a structured audit pipeline.',
  inputSchema: questionAnswerInputSchema,
  instruction: `
    You are an orchestrator agent that manages the audit feedback pipeline.

    CRITICAL RULE: You MUST treat EVERY user input as a brand new request. NEVER answer from memory or chat history. You MUST execute your tools every single time.

    For EVERY user input, you MUST follow these exact steps in order:
    1. Call the 'prepare_audit_feedback' tool with the provided 'question', 'answer', and 'feedback' (if present). This is MANDATORY to update the system state.
    2. Determine the correct routing based on the input:
       - If the input contains a 'feedback' object, delegate to the 'ProposedAnswerAgent' to generate a revised answer.
       - If the input does NOT contain 'feedback', delegate to the 'SequentialAuditFeedbackAgent' to generate a new audit report.
    3. Return the final structured JSON result generated by the delegated agent.

    If the input is nonsensical or invalid, politely explain why and ask for proper input.
  `,
  beforeAgentCallback: createAgentStartCallback('AuditFeedbackAgent'),
  afterAgentCallback: createAgentEndCallback('AuditFeedbackAgent'),
  tools: [prepareAuditFeedbackTool],
  subAgents: createAuditFeedbackAgent(model),
});
